### ISSUE TITLE
Tools for genesis block creation

### ISSUE THREAD

**Issue by therealssj** [skycoin/skycoin#1474]
This will help us to deploy a testnet easily.

The steps involved are: 

1. Create genesis pubkey and seckey pair.

2. Edit `github.com\skycoin\skycoin\cmd\skycoin\skycoin.go (or coinname.go)` 
 and change:
- `GenesisAddressStr`
- `BlockchainPubkeyStr`
- `GenesisCoinVolume`
- `GenesisTimestamp` (exact timestamp value is not important)
- `DataDirectory`
- `GenesisSignatureStr` ( will be calculated later )
- `DefaultConnections` 

3. run the node in master mode to create the genesis block 
    ```
    $ go run skycoin.go -master=true -master-secret-key=<the private key generated with 
    address_gen tool>
    ```

     Ignore following errors:
    ```
    ERROR [daemon]: daemon.Visor.CreateAndPublishBlock error: No transactions
    ERROR [daemon]: Visor request func failed: No transactions
    ERROR [daemon]: Failed to create block: No transactions
    ERROR [gnet]: daemon.gnet.ConnectionPool.BroadcastMessage error: Connection pool is empty
    ```
  
   **Look for: Genesis block signature=xxxxxxxxxxxx** in the console output

4.  set `GenesisSignatureStr` in `github.com\skycoin\skycoin\cmd\skycoin\skycoin.go (or coinname.go)`  

## Tasks
- [ ] create a `template` folder at the top level.
- [ ] place the config file `fiber.toml` in the repo root
- [ ] create a new package `skycoin` inside it create a `config.go` with a config struct which will hold the parameters as defined in step 2. This package will read the `fiber.toml` file and build a config struct from it.
- [ ] create a cli tool which will use the `skycoin` package to bootstrap a new coin under `cmd/<coin>/<coin>.go`
- [ ] add a `MAKE` command to run the tool

## Issues:
- https://github.com/skycoin/skycoin/issues/1485
- https://github.com/skycoin/skycoin/issues/1484

**Comment by olemis** [comment]
If you plan to generate a go file maybe you'll find [jennifer](https://github.com/dave/jennifer) useful .
