### ISSUE TITLE
Testnet deploy scripts

### ISSUE THREAD

**Issue by olemis** [skycoin/skycoin#828]
#Implement script to deploy Docker containers running Skycoin (mainnet / testnet) . The configuration would be similar to this 

- [X] a ~(Python / Bash)~ Golang script to generate a (parameterized, e.g. number of nodes) docker-compose.yml
- [X] the docker-compose.yml to setup the testnet network consisting in :
- [X] a virtual network
- [X] <N> nodes running with no browser
- [X] 1 container running browser 
- [x] detect testnet script path Cc @olemis
- [ ] 1 container running a centralized logging server ( ~[logstash](https://www.elastic.co/guide/en/logstash/current/docker.html)~ vs ~[gollum]( https://github.com/trivago/gollum)~ vs [logspout](https://github.com/gliderlabs/logspout)+[oklog](https://github.com/oklog/oklog) 👍  ) Cc @stdevMauricio
- [x] merge with testnet branch Cc @olemis see comments in skycoin/services#12
- [x] load default connections (peers) from txt file Cc @olemis
- [ ] separate logging output (docker-compose stdout + [logspout](https://github.com/gliderlabs/logspout) ) Cc @stdevMauricio
- [x] container to run https://github.com/skycoin/skycoin-explorer Cc @stdevMauricio see skycoin/skycoin-explorer#110
- [ ] option to load existing db Cc @stdevMauricio
- [x] `dependency not vendored: gopkg.in/yaml.v2` Need to update dependencies following these [instructions](https://github.com/skycoin/skycoin#dependency-management) Cc @stdevMauricio 
- [x] Do `gofmt -w docker/images/testnet/testnet.go` as part of `make format` Cc @olemis
- ~deployment options (e.g. local, AWS, Azure, ...)~
- [ ] Replace all relative paths in `testnet.go` script (... and beyond ...) by using `projectPath` variable pointing at a working copy of skycoin/skycoin repository checked out in local file system Cc @stdevMauricio
- [x] Fix [testnet issue with pubkey](https://github.com/skycoin/skycoin/issues/828#issuecomment-364476592) Cc @olemis
- [ ] Enforce usage of different address `Version` for mainnet vs testnet ( Cc @olemis )
- [ ] Options to log events in [logspout format](https://github.com/gliderlabs/logspout#raw-format) (.Cc @olemis ) 
- [ ] Further info when `-version` flag (see #1390) is specified.
  * [ ] Adress prefix (see #988 )
  * [ ] Address version (mainnet vs testnet vs simtestnet)
- [ ] initialize genesis block for testnet
- [ ] create new blockchain from scratch using genesis creation tool (see #1468 )

**Comment by gz-c** [comment]
If possible use go to generate the yaml file, maybe with their template engine

**Comment by olemis** [comment]
The merge for testnet is close to be ready

[This branch](https://github.com/simelo/skycoin/tree/olemis_t828_skycoin_docker_testnet) has the whole set of changes . Testnet merge plus docker scripts to deploy via docker-compose  [This other branch](https://github.com/simelo/skycoin/tree/olemis_t828_skycoin_testnet) has the testnet merge and nothing else (i.e. no Docker scripts, etc)

`make test` succeeds for both RFC => but further testing might be needed

**Comment by olemis** [comment]
We'll be working on those branches in parallel . Base branch moved to point to testnet

**Comment by stdevMauricio** [comment]
I'm having this issue with the latest testnet code
skycoin --web-interface-addr=0.0.0.0 --master --master-secret-key=00b2cd5740d50ba96071fb761f63a233317cc01cf3777d32240ee206897ffdeb --launch-browser=false --master-public-key=03cb5837ae319051203771e38b0413a6a1afc401ff5f4e8115e0766b71abafc1e3 
2018/02/09 09:46:29 Created data directory /home/mauricio/~/.skycoin
abs path: /home/mauricio/Go/src/github.com/skycoin/skycoin/cmd/skycoin/src/gui/static
runtime.Caller= /home/mauricio/Go/src/github.com/skycoin/skycoin/cmd/skycoin/skycoin.go 
Filepath Directory= src/gui/static 
Filepath Absolute Directory= /home/mauricio/Go/src/github.com/skycoin/skycoin/cmd/skycoin/src/gui/static 
Working Directory= /home/mauricio/Go/src/github.com/skycoin/skycoin/cmd/skycoin 
Runtime Filename= /home/mauricio/Go/src/github.com/skycoin/skycoin/cmd/skycoin/skycoin.go 
Runtime Directory= /home/mauricio/Go/src/github.com/skycoin/skycoin/cmd/skycoin 
ResolveResourceDirectory: static resource dir= /home/mauricio/Go/src/github.com/skycoin/skycoin/src/gui/static 
2018/02/09 09:46:29 Full address: http://0.0.0.0:6420
[skycoin.visor:DEBUG] Creating new visor
[skycoin.visor:DEBUG] Visor is master
[skycoin.crypto:CRITICAL] PubKeyFromSecKey, attempt to load null seckey, unsafe
[skycoin.main:ERROR] recover: PubKeyFromSecKey, attempt to load null seckey, unsafe
stack:goroutine 1 [running]:
runtime/debug.Stack(0xc4201369d8, 0x8781c0, 0xc4200453b0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
main.Run.func1()
	/home/mauricio/Go/src/github.com/skycoin/skycoin/cmd/skycoin/skycoin.go:584 +0x57
panic(0x8781c0, 0xc4200453b0)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/skycoin/skycoin/vendor/github.com/op/go-logging.(*Logger).Panic(0xc42006f680, 0xc420136c00, 0x1, 0x1)
	/home/mauricio/Go/src/github.com/skycoin/skycoin/vendor/github.com/op/go-logging/logger.go:182 +0x163
github.com/skycoin/skycoin/src/cipher.PubKeyFromSecKey(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc42006f700)
	/home/mauricio/Go/src/github.com/skycoin/skycoin/src/cipher/crypto.go:84 +0x294
github.com/skycoin/skycoin/src/visor.Config.Verify(0x20f4d376c5280301, 0x3a1781a9582068e7, 0xbf55ffc57c4c374b, 0xe6bb5970f53c4d39, 0x6a45, 0x0, 0x0, 0x0, 0x0, 0xa, ...)
	/home/mauricio/Go/src/github.com/skycoin/skycoin/src/visor/visor.go:161 +0x78
github.com/skycoin/skycoin/src/visor.NewVisor(0x20f4d376c5280301, 0x3a1781a9582068e7, 0xbf55ffc57c4c374b, 0xe6bb5970f53c4d39, 0x6a45, 0x0, 0x0, 0x0, 0x0, 0xa, ...)
	/home/mauricio/Go/src/github.com/skycoin/skycoin/src/visor/visor.go:248 +0xa8
github.com/skycoin/skycoin/src/daemon.NewVisor(0x20f4d376c5280301, 0x3a1781a9582068e7, 0xbf55ffc57c4c374b, 0xe6bb5970f53c4d39, 0x6a45, 0x0, 0x0, 0x0, 0x0, 0xa, ...)
	/home/mauricio/Go/src/github.com/skycoin/skycoin/src/daemon/visor.go:88 +0x158
github.com/skycoin/skycoin/src/daemon.NewDaemon(0x2, 0x0, 0x0, 0x3e80, 0xc420017700, 0x19, 0x12a05f200, 0x12a05f200, 0x10, 0x10, ...)
	/home/mauricio/Go/src/github.com/skycoin/skycoin/src/daemon/daemon.go:231 +0xfe
main.Run(0xc98920)
	/home/mauricio/Go/src/github.com/skycoin/skycoin/cmd/skycoin/skycoin.go:636 +0x734
main.main()
	/home/mauricio/Go/src/github.com/skycoin/skycoin/cmd/skycoin/skycoin.go:794 +0x3d

**Comment by olemis** [comment]
@stedevMauricio I added some commits in `olemis_t828_skycoin_docker_testnet` branch. Please update yours . Besides , review the TODO items in issue description above .

**Comment by stdevMauricio** [comment]
I changed a lot of the code, but not so much the functionality. Now the code is much more readable and flexible. I just uploaded a README.md with the instructions to launch a testnet.

**Comment by olemis** [comment]
#1671 requests for a testnet
